### ISSUE TITLE
Client interface

### ISSUE THREAD

**Issue by rocbr** [TechnitiumSoftware/Mesh#1]
First of all, congratulations for your project. A true p2p high level end-to-end encryption message system is awesome.

What kind of client are you planning? Android, Linux, Web? All of them?

**Comment by ShreyasZare** [comment]
Thanks for the compliments. 

The code base is written using .NET standard and is cross platform. The first client that I am working on will be Windows based. Later, mobile clients can be written using same code base. 

A web based client is also being thought of so that the client can work on Linux & MacOS since .NET Core lacks cross platform GUI library. With this, the client will run in background on the computer and can be accessed using any web browser on the same computer.
